// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

// Detect staging by env var or hostname
const isStaging =
  import.meta.env?.VITE_ENVIRONMENT === 'staging' ||
  (typeof window !== 'undefined' &&
    (window.location.hostname.includes('staging') ||
     window.location.hostname.includes('lovableproject')));

// ---- Production (MAIN) ----
const PROD_SUPABASE_URL = 'https://fezmgnixfujyfdxcwyol.supabase.co';
const PROD_SUPABASE_KEY =
  'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImZlem1nbml4ZnVqeWZkeGN3eW9sIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTExMjA5ODgsImV4cCI6MjA2NjY5Njk4OH0.ncyTzxooOjBuhQknMxNn1Cf2mFx5CoUUJBHEmWVFZgc';

// ---- Staging ----
const STAGING_SUPABASE_URL = 'https://zanlercqmdxgydtaqzni.supabase.co';
const STAGING_SUPABASE_KEY =
  'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InphbmxlcmNxbWR4Z3lkdGFxem5pIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjA1Mzk0MzMsImV4cCI6MjA3NjExNTQzM30.6P5nA_2uVyQXyvKhOJNu-2_-LeO66CGJAZ42SfJay7U';

// Pick env
const SUPABASE_URL = isStaging ? STAGING_SUPABASE_URL : PROD_SUPABASE_URL;
const SUPABASE_ANON_KEY = isStaging ? STAGING_SUPABASE_KEY : PROD_SUPABASE_KEY;

// Export client
export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_ANON_KEY, {
  auth: {
    storage: typeof window !== 'undefined' ? window.localStorage : undefined,
    persistSession: true,
    autoRefreshToken: true,
  },
});
